### ISSUE TITLE
sbt eclipe is not valid command

### ISSUE THREAD

**Issue by Dhruva539** [sbt/sbteclipse#320]
I have installed sbt 0.13.12.1 in windows 10 and configured pulhins.sbt by adding below line.

addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "4.0.0")

And also put same plugin file in my project folder as well, When i run "sbt eclipse" on dos shell(SBT environment variables are set up) ,getting sbt eclipse is not valid.

C:\Users\Pranavi\Documents\scala-space\simple-scala-sbt>sbt eclipse
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading global plugins from C:\Users\Pranavi.sbt\0.13\plugins
[info] Set current project to simple-scala-sbt (in build file:/C:/Users/Pranavi/Documents/scala-space/simple-scala-sbt/)
[error] Not a valid command: eclipse (similar: help, alias)
[error] Not a valid key: eclipse (similar: deliver, licenses, clean)
[error] eclipse
[error]        ^

please advise

**Comment by Blaisorblade** [comment]
`plugins.sbt` must not be the project folder, but in its `project/` subdirectory.

**Comment by helloBangalore** [comment]
Hi Blaisorblade,

Your suggestion is not working.Do you have any other suggestion.
Please advise.

**Comment by Blaisorblade** [comment]
> Your suggestion is not working.Do you have any other suggestion.

"X is not working" without details such as error messages. is not very helpful. As in, others literally can't help you.

There are so many unknowns and chances for typos it's hard to tell. Maybe on Gitter (https://gitter.im/sbt/sbt) there are more chances?
In any case, you need to be more accurate with typos—I usually recommend to use copy-n-paste to avoid them.

Generic advice: disable other global plugins, by say moving `C:\Users\Pranavi.sbt\0.13` elsewhere to clean things up, then start on an empty project—put it in say `C:\Users\Pranavi\Documents\scala-space\empty-scala-sbt`, and put just `addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "4.0.0")` inside `C:\Users\Pranavi\Documents\scala-space\empty-scala-sbt\project\plugins.sbt`.

Or rather, use the latest version of the plugin by writing _INSTEAD_ 
`addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "5.1.0")` in
`C:\Users\Pranavi\Documents\scala-space\empty-scala-sbt\project\plugins.sbt`.

If that doesn't work, you might have a better chance on Gitter if somebody has time, you work at troubleshooting with sufficient care and provide sufficient info.

**Comment by PanAeon** [comment]
"sbt eclipe" or "sbt eclipse" :) ?

**Comment by Bibudesh** [comment]
If you are following any old Scala Tutorial then highly likely that the plugins are placed in a wrong folder.
In older version it was recommended to put the plugins into folder <workspace>/project/**plugins**/plugins.sbt
Remove the folder plugins and place plugins.sbt directly into project and it will work. i.e. 
<workspace>/project/plugins.sbt

**Comment by Blaisorblade** [comment]
This issue is a stale support request (from 2016); please close. I'm unsubscribing.
