### ISSUE TITLE
relocate from typesafehub org to Lightbend org

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbteclipse#357]

**Comment by benmccann** [comment]
I don't think I have sufficient permissions to do this. Perhaps @jsuereth can do it

**Comment by SethTisue** [comment]
@eed3si9n @dwijnand or would sbt org make more sense...?

I don't have superpowers in the typesafehub org, but there are some folks at Lightbend who do

**Comment by eed3si9n** [comment]
Let's move it to sbt organization, like the rest of plugins.

**Comment by eed3si9n** [comment]
Moved.
