### ISSUE TITLE
sbteclipse installation i do not understand

### ISSUE THREAD

**Issue by santo18** [sbt/sbteclipse#361]
Hi,
I'm completely new about sbt, I do not understand the installation instructions of the plugin in eclipse.

After downloading the file sbteclipse-master.zip where to put this file? and what steps should I follow in eclipse to install it?

If I do a normal the manual installation procedure for eclipse plugins, I select from the eclipse menu

"help" > "Install new software" and then click on "add" and then on "Archive"

when I select the file sbteclipse-master.zip an eclipse message tells me "Could not find jar"

What is the detailed procedure to follow from the beginning? Where can I find it?

Thanks so much

**Comment by marcenuc** [comment]
sbteclipse is a sbt plugin, not an eclipse plugin. There's nothing to install on eclipse. You only need to enable the plugin on sbt and it will be automatically downloaded by sbt. Please read the README file for further instructions.
