### ISSUE TITLE
sbteclipse 5.2.5?

### ISSUE THREAD

**Issue by bdkent** [sbt/sbteclipse#363]
The `README.md` has a section for "sbteclipse 5.2.5 and up", but no 5.2.5+ version seems to exist.

There is nothing tagged beyond 5.2.4 on [github releases](https://github.com/sbt/sbteclipse/releases) or [bintray](https://bintray.com/sbt/sbt-plugin-releases/sbteclipse).

Is there a roadmap for a 5.2.5 release?

**Comment by benmccann** [comment]
I've updated the README
