### ISSUE TITLE
Support for Java 9 and above?

### ISSUE THREAD

**Issue by slisaasquatch** [sbt/sbteclipse#368]
Looks like the latest version in `EclipseExecutionEnvironment` is still `JavaSE18`.

**Comment by benmccann** [comment]
I'm not exactly sure what the `executionEnvironment` field is used for. It looks to me like if you don't set it and use the default value of `None` then everything generally works, which is probably why no one else has reported problems with Java 9. I'm curious if you can leave it unset or if you can help explain what it's used for?

**Comment by slisaasquatch** [comment]
You are right, leaving it unset works. So why does that field exist if it's not doing much? I originally assumed that this project didn't support Java 9 because that field was capped at Java 8.
Anyway, I'll close the ticket.

**Comment by benmccann** [comment]
I don't know. That was there before I started helping with this project

My guess is that if you have multiple JREs installed that field allows you to specify a different one to use
