### ISSUE TITLE
Missing Scala lib in .classpath

### ISSUE THREAD

**Issue by liteultom** [sbt/sbteclipse#374]
Using Java 8, Play Framework 2.4, Scala 2.11.7 and sbteclipse 5.2.4

**Problem:** When I eclipsify my project, I get a mostly correct `.classpath` file except that the scala lib paths are missing.

**Consequences:** When I compile and run my project with sbt, everything is fine. But my IDE (vscode) displays some errors because it cannot find the scala libs

**Temporary fix:** manually add two lines to the `.classpath` file to include `scala-library` and `scala-reflect` from the jars in my `/home/[USER]/.ivy2/cache/` folder

Is this expected behavior because the source are not Java ? If not, any solution to that problem ? It's not a huge one since I can compile and run, and the fix for vscode is quick and easy, but it's also a bit dirty.

**Comment by benmccann** [comment]
Here's some relevant settings:

https://github.com/sbt/sbteclipse/wiki/Using-sbteclipse#projectflavor
https://github.com/sbt/sbteclipse/wiki/Using-sbteclipse#withbundledscalacontainers

**Comment by liteultom** [comment]
Awesome, thank you ! using:
```
EclipseKeys.withBundledScalaContainers := false
```
and then reloading the `build.sbt` file did the trick !
